services:
  - type: web
    name: buildnest-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: api.buildnest.in
      - key: CORS_ALLOWED_ORIGINS
        value: https://buildnest.in,https://www.buildnest.in
      - key: DATABASE_URL
        sync: false # You paste the Neon connection string here in Render dashboard
      - key: JWT_ACCESS_LIFETIME_MIN
        value: "60"
      - key: JWT_REFRESH_LIFETIME_DAYS
        value: "30"
    healthCheckPath: /api/v1/health/
