# Generated by Django 5.2.16 on 2026-07-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(choices=[('architect', 'Architect'), ('civil_engineer', 'Civil Engineer'), ('interior_designer', 'Interior Designer'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('mason', 'Mason'), ('general', 'General Contractor')], default='general', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='projects.project')),
            ],
            options={
                'ordering': ['trade', 'name'],
            },
        ),
    ]
