# Generated by Django 5.2.16 on 2026-07-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel'), ('bricks', 'Bricks & Blocks'), ('sand', 'Sand & Aggregate'), ('tiles', 'Tiles & Flooring'), ('wood', 'Wood & Timber'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('paint', 'Paint & Finishing'), ('misc', 'Miscellaneous')], default='misc', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('bags', 'Bags'), ('kg', 'Kg'), ('tons', 'Tons'), ('sqft', 'Sq. Ft.'), ('nos', 'Nos.'), ('meters', 'Meters'), ('liters', 'Liters'), ('cft', 'Cu. Ft.')], default='nos', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('delivery_status', models.CharField(choices=[('required', 'Required'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('installed', 'Installed')], default='required', max_length=20)),
                ('ordered_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
