import type { Expense, ExpenseCategory } from "@/features/expenses/types";

/** Dummy expense ledger for Willow Creek Residence. Swaps to the API layer later. */

export const expenseCategories: ExpenseCategory[] = [
  "Structure",
  "Electrical",
  "Plumbing",
  "Interior",
  "HVAC",
  "Landscaping",
  "Permits & fees",
  "Contingency",
];

export const expenseStats = {
  /** July 2026 month-to-date spend (matches dashboard actuals). */
  thisMonth: 184000,
  pendingCount: 3,
  pendingTotal: 58000,
  largestExpense: 89000,
  largestExpenseLabel: "Hardwood flooring — white oak",
};

export const expenses: Expense[] = [
  {
    id: "exp_01",
    date: "2026-07-16",
    description: "Kitchen cabinetry deposit",
    category: "Interior",
    vendor: "WoodCraft Cabinetry",
    amount: 48500,
    status: "paid",
  },
  {
    id: "exp_02",
    date: "2026-07-15",
    description: "Recessed lighting fixtures (24×)",
    category: "Electrical",
    vendor: "SparkLine Electric",
    amount: 19200,
    status: "pending",
  },
  {
    id: "exp_03",
    date: "2026-07-14",
    description: "Master bath tile — porcelain",
    category: "Interior",
    vendor: "Bengaluru Tile & Stone",
    amount: 32400,
    status: "pending",
  },
  {
    id: "exp_04",
    date: "2026-07-11",
    description: "Plumbing fixture set — master bath",
    category: "Plumbing",
    vendor: "Sharma Plumbing",
    amount: 27800,
    status: "paid",
  },
  {
    id: "exp_05",
    date: "2026-07-09",
    description: "HVAC balancing pre-test",
    category: "HVAC",
    vendor: "Kumar Mechanical",
    amount: 6400,
    status: "pending",
  },
  {
    id: "exp_06",
    date: "2026-07-08",
    description: "Interior paint — Level 2",
    category: "Interior",
    vendor: "ProPaint Bengaluru",
    amount: 21500,
    status: "paid",
  },
  {
    id: "exp_07",
    date: "2026-07-03",
    description: "Electrical permit E-2094 fee",
    category: "Permits & fees",
    vendor: "BBMP",
    amount: 4800,
    status: "reimbursed",
  },
  {
    id: "exp_08",
    date: "2026-07-01",
    description: "Drywall finishing — Level 2",
    category: "Interior",
    vendor: "GypsumPro Drywall",
    amount: 23400,
    status: "paid",
  },
  {
    id: "exp_09",
    date: "2026-06-27",
    description: "Hardwood flooring — white oak",
    category: "Interior",
    vendor: "TimberMart Supply",
    amount: 89000,
    status: "paid",
  },
  {
    id: "exp_10",
    date: "2026-06-24",
    description: "Tankless water heater + install",
    category: "Plumbing",
    vendor: "Sharma Plumbing",
    amount: 23500,
    status: "paid",
  },
  {
    id: "exp_11",
    date: "2026-06-19",
    description: "Landscape grading & site prep",
    category: "Landscaping",
    vendor: "GreenScape Landscaping",
    amount: 18500,
    status: "paid",
  },
  {
    id: "exp_12",
    date: "2026-06-16",
    description: "Electrical panel upgrade — 200A",
    category: "Electrical",
    vendor: "SparkLine Electric",
    amount: 34000,
    status: "paid",
  },
  {
    id: "exp_13",
    date: "2026-06-12",
    description: "HVAC ductwork — Level 2",
    category: "HVAC",
    vendor: "Kumar Mechanical",
    amount: 41500,
    status: "paid",
  },
  {
    id: "exp_14",
    date: "2026-06-09",
    description: "Interior doors (14×)",
    category: "Interior",
    vendor: "TimberMart Supply",
    amount: 30800,
    status: "reimbursed",
  },
  {
    id: "exp_15",
    date: "2026-06-04",
    description: "Framing punch-list labor",
    category: "Structure",
    vendor: "Mehra Framing Co.",
    amount: 16500,
    status: "paid",
  },
];
