/** Realistic dummy data for the materials page. Swaps to the API layer later. */

import type { Material } from "./types";

export const materialCategories = [
  "Lumber",
  "Electrical",
  "Plumbing",
  "Finishes",
  "Masonry",
  "Roofing",
  "Drywall",
  "Hardware",
  "HVAC",
] as const;

export const materials: Material[] = [
  {
    id: "mat_01",
    name: "Oak hardwood flooring",
    category: "Finishes",
    quantity: 1450,
    unit: "sq ft",
    unitCost: 87.5,
    supplier: "Bengaluru Timber Co.",
    status: "ordered",
  },
  {
    id: "mat_02",
    name: "Quartz countertop slabs",
    category: "Finishes",
    quantity: 4,
    unit: "slabs",
    unitCost: 11800,
    supplier: "StoneWorks Masonry",
    status: "pending",
  },
  {
    id: "mat_03",
    name: "Interior paint — Swiss Coffee",
    category: "Finishes",
    quantity: 22,
    unit: "L",
    unitCost: 420,
    supplier: "ColorKart Supply",
    status: "delivered",
  },
  {
    id: "mat_04",
    name: "12/2 Romex wire (250 ft)",
    category: "Electrical",
    quantity: 6,
    unit: "rolls",
    unitCost: 1180,
    supplier: "Volt Electric",
    status: "delivered",
  },
  {
    id: "mat_05",
    name: "Recessed LED fixtures",
    category: "Electrical",
    quantity: 38,
    unit: "units",
    unitCost: 240,
    supplier: "Volt Electric",
    status: "ordered",
  },
  {
    id: "mat_06",
    name: 'PEX tubing 3/4"',
    category: "Plumbing",
    quantity: 12,
    unit: "rolls",
    unitCost: 890,
    supplier: "Sharma Plumbing",
    status: "delivered",
  },
  {
    id: "mat_07",
    name: "Master bath fixture set",
    category: "Plumbing",
    quantity: 3,
    unit: "sets",
    unitCost: 6400,
    supplier: "Sharma Plumbing",
    status: "backordered",
  },
  {
    id: "mat_08",
    name: "Shaker cabinet doors",
    category: "Lumber",
    quantity: 42,
    unit: "units",
    unitCost: 960,
    supplier: "OakLine Carpentry",
    status: "ordered",
  },
  {
    id: "mat_09",
    name: 'Drywall sheets 5/8"',
    category: "Drywall",
    quantity: 160,
    unit: "sheets",
    unitCost: 155,
    supplier: "BuildRight Supply",
    status: "delivered",
  },
  {
    id: "mat_10",
    name: "Architectural shingles",
    category: "Roofing",
    quantity: 48,
    unit: "bundles",
    unitCost: 380,
    supplier: "Summit Roofing",
    status: "delivered",
  },
  {
    id: "mat_11",
    name: "Limestone veneer",
    category: "Masonry",
    quantity: 320,
    unit: "sq ft",
    unitCost: 112.5,
    supplier: "StoneWorks Masonry",
    status: "ordered",
  },
  {
    id: "mat_12",
    name: "HVAC duct kit — Level 2",
    category: "HVAC",
    quantity: 1,
    unit: "kit",
    unitCost: 23400,
    supplier: "Kumar Mechanical",
    status: "delivered",
  },
  {
    id: "mat_13",
    name: "Door hardware — matte black",
    category: "Hardware",
    quantity: 18,
    unit: "sets",
    unitCost: 540,
    supplier: "BuildRight Supply",
    status: "pending",
  },
  {
    id: "mat_14",
    name: 'Baseboard trim 5 1/4"',
    category: "Lumber",
    quantity: 620,
    unit: "lin ft",
    unitCost: 34,
    supplier: "Bengaluru Timber Co.",
    status: "pending",
  },
];

export const materialStats = {
  totalCost: materials.reduce((sum, m) => sum + m.quantity * m.unitCost, 0),
  pendingDeliveries: materials.filter((m) => m.status === "pending" || m.status === "backordered")
    .length,
  itemsOrdered: materials.filter((m) => m.status === "ordered").length,
};
